services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./ch4-bookstore:/app
    command: gunicorn django_project.wsgi:application -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-(l1a4)2!je_)1+nw@3618--&+##u6=vk=bk1yww_2ubhat6gkd"
      - "DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0" 
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" 
      - "DJANGO_SECURE_HSTS_PRELOAD=False" 
      - "DJANGO_SESSION_COOKIE_SECURE=False" 
      - "DJANGO_CSRF_COOKIE_SECURE=False" 
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mypassword"
      - "POSTGRES_DB=mydb"

volumes:
  postgres_data: